t = [[[[True, True]],2,0,1], 
     [[[True, True, True], [False, True, False],[False, True, False]],5,2,5], 
     [[[True, False, False],[True, False, False], [True, True, True]],4,1,2], 
     [[[True, True, True]],2,0,2],
     [[[True, False, True], [True, True, True]],1,0,2],
     [[[True, False, True], [True, True, True],[False, True, False]],3,2,6],
     [[[False, False, True, False, False], [True, True, True, True, True], [False, False, True, False, False]],1,1,4],
     [[[False, True, True, True, False], [True, True, True, True, True], [False, True, True, True, False]],5,1,3],
     [[[True, True, True, True], [True, False, False, False]],10,2,3],
     [[[True, False, False],[True, False, False], [True, True, True]],4,2,6],
     [[[True, True, False], [False, True, True]],3,1,2],
     [[[True, True, True], [False, True, False],[False, True, False],[False, True, False]],7,2,2],
     [[[True, True, True, True]],3,1,3],
     [[[False, True, False, False], [True, True, True, True]],3,1,4],
     [[[True, True, False], [False, True, True]],7,3,6],
     [[[True, True, True, True], [True, False, False, True]],1,1,5],
     [[[True, True, True], [False, True, False], [True, True, True]],2,0,3],
     [[[False, True, False], [True, True, True], [False, True, False],[False, True, False]],0,1,3],
     [[[True, True], [True, True]],6,2,5],
     [[[True, False], [True, False],[True, True], [True, True]],10,3,5],
     [[[False, True, True, True, True], [True, True, False, False, False]],2,1,3],
     [[[False, True, True, False],[True, True, True, True]],7,2,4],
     [[[False, False, True], [False, True, True], [True, True, False]],10,3,4],
     [[[True, True, True, False],[False, True, True, True]],4,0,2],
     [[[False, True, True], [True, True, True]],2,0,2],
     [[[True, True, True], [False, True, False]],2,0,2],
     [[[False, False, False, True], [True, True, True, True], [True, False, False, False]],1,0,2],
     [[[True, False], [True, True]]3,0,1],
     [[[False, True, True],[True, True, False], [True, True, False]],8,3,6],
     [[[True, True, True, True, True]]7,1,1],
     [[[False, True, False, False], [True, True, True, True], [False, False, True, False]],2,0,1],
     [[[False, True, False],[True, True, True], [False, True, False]],5,2,4],
     [[[True, False], [True, True]],1,0,3]
     ]
